### ISSUE TITLE
live preview

### ISSUE THREAD

**Issue by buhman** [ptpb/pb#113]
I hear people want this.

The idea is:

* you write your markdown or whatever
* you can see (perhaps even as you type or something) what the rendered output looks like

Why I would be ok with not doing this:

* involves adding client-side js (arguably completely disqualifying pb from being 'lightweight')
* you could accomplish the same thing more or less just by repeated submissions and forward/backward in the browser

**Comment by buhman** [comment]
If we do this, I'd like to write this in AngularJS. Would create precedent for other potentially interesting things as well.

**Comment by tb01110100** [comment]
I'd love this. I hope this happens.

**Comment by buhman** [comment]
What I have so far is previewable here: https://buhman.org/pbc/

@silverp1; I suggest we create a new repo for this sub-project; silverp1/pbc perhaps. Or, maybe move this all to the 'pb' organization, so that the C rewrite can live there too.

@tb01110100; what do you think?

**Comment by buhman** [comment]
https://github.com/ptpb/pbc
