### ISSUE TITLE
ttyrec handler

### ISSUE THREAD

**Issue by HalosGhost** [ptpb/pb#117]
There are a few websites (which are essentially limited pastebins) which have allowed you to upload a session recorded with ``ttyrec`` and share it (just like you would share a paste in ``pb`` now). The features these sites offer include play/pause/restart (some even include options to make playback faster or slower than real-time) along with the full text of the session being copyable (this should be one of the easiest features considering that the format ``ttyrec`` outputs actually includes all the text.

``pb``, as it does not truly care about what kind of data is pasted to it, an already take ``ttyrec`` files as pastes. And users _could_ fetch one of these files and pipe it into ``ttyplay``, but having a handler (similar to the rst handler) that allows for in-browser playback of these pastes could be incredibly helpful.

**Comment by HalosGhost** [comment]
As a small note of clarification: the rendering does not need to happen on the server side (which, I believe deviates from how the rst/mdown handler is done). The rendering can happen client-side with a JS library, assuming one exists (which seems likely given the availability of this feature in other more limited pastebins).

**Comment by buhman** [comment]
I re-re-looked at this, and it seems too messy. I would consider contributions or specific suggestions, but I won't be initiating the work on this myself.

**Comment by buhman** [comment]
asciinema-player added in 6bac61cf526970f5c0244120a9d11effbddce150
