### ISSUE TITLE
Package for Arch Linux

### ISSUE THREAD

**Issue by HalosGhost** [ptpb/pb#118]
The reference host of ``pb`` ([ptpb](https://ptpb.pw)) is great, but there are some cases where I would find it helpful to be able to install my own copy of ``pb`` to be hosted wherever I so choose; e.g., I could even imagine deploying ``pb`` as a private service to be used on an internal network in the company I work for.

Offering a ``PKGBUILD`` to build and package ``pb`` for Arch would be deeply appreciated.

**Comment by buhman** [comment]
695502420fe117fe1fb7ad7448262152f5a112fc

**Comment by buhman** [comment]
https://aur.archlinux.org/packages/pb-git
