### ISSUE TITLE
Support 64 MiB pastes

### ISSUE THREAD

**Issue by HalosGhost** [ptpb/pb#119]
At the moment, ``pb`` supports pastes up to 60 MiB in size.

That is, ``62914560`` bytes. Look how awful that number is!

Would it not be dramatically rounder and prettier to allow for 64 MiB; i.e., ``67108864`` (or ``2 ^ 26``) bytes?

**Comment by buhman** [comment]
Fixed:

```shell
$ dd if=/dev/zero bs=67108865 count=1 2>/dev/null | curl -D - --data-binary @- https://ptpb.pw'
HTTP/1.1 413 Request Entity Too Large
Server: nginx/1.6.2
Date: Thu, 23 Apr 2015 04:48:30 GMT
Content-Type: text/html
Content-Length: 198
Connection: close

<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```

```shell
$ dd if=/dev/zero bs=67108864 count=1 | curl -D - --data-binary @- https://ptpb.pw
HTTP/1.1 100 Continue

HTTP/1.1 400 BAD REQUEST
Server: nginx/1.6.2
Date: Thu, 23 Apr 2015 04:50:00 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 6
Connection: keep-alive
Access-Control-Allow-Origin: *
X-Varnish: 3310705
Age: 0
Via: 1.1 varnish-v4

Nope.
```

It's funny because you get to watch how long it takes werkzeug to parse a 64MiB-of-zeros request body now, before pb says 'Nop'.

**Comment by HalosGhost** [comment]
Lol, so ``pb``'s max request is 64 MiB now, but werkzeug can't handle it?

**Comment by buhman** [comment]
Erm no. I suspect werkzeug is not compliant with the HTTP spec, and parsed the zeros out of existance.
