### ISSUE TITLE
URL shortener does not return UUID

### ISSUE THREAD

**Issue by escondida** [ptpb/pb#124]
When shortening a URL with, say,
    curl -F 'c=http://somelongwebsite.com' https://ptpb.pw/u
pb returns only the shortened URL, not a UUID for later updates/removal as normal.

**Comment by buhman** [comment]
Shorturls don't support updates--showing the UUID is only half the problem.

Updates only make sense for vanity pastes, as shortIDs are derived from the sha1 of the content. See #122.

I could be persuaded to refactor pb in either direction with sufficient justification.

**Comment by escondida** [comment]
Interesting. That definitely makes sense. It might be good to return the UUID if only for the sake of deleting the associated paste...but on the other hand, I suppose that even a long URL doesn't exactly waste too much server space for the host.

**Comment by buhman** [comment]
Not a bug.
