### ISSUE TITLE
Centering paste areas when lexed

### ISSUE THREAD

**Issue by HalosGhost** [ptpb/pb#126]
cf. [this paste](https://ptpb.pw/bF2K.log/)

This paste has long lines, and as a result takes up more horizontal space than it would seem is typical. However, the paste area does not account for the extra width to center itself correctly. At a guess, this is because the paste area is shifted right by a static size rather than centering itself dynamically. The result is ugly and not ideal.

A screenshot for simplicity:

![b04949bc-56df-4da5-bf98-cb8adb74cf18](https://ptpb.pw/iKYj.png)

**Comment by buhman** [comment]
Lolbootstrap.

**Comment by buhman** [comment]
Fixed by 635f974bfbc7b6fce2782d91c29db4385a9d286c
