### ISSUE TITLE
Complete breakage when displaying SVGs

### ISSUE THREAD

**Issue by HalosGhost** [ptpb/pb#127]
If you go to, for example, [this paste](https://ptpb.pw/dVon.svg), you get the following error:

![0881c954-cd52-4dfe-8543-68bbb5dd48f4](https://ptpb.pw/TCWh.png)

**Comment by buhman** [comment]
That error looks like a browser/client-side error. That paste doesn't appear to exist.

**Comment by HalosGhost** [comment]
Can no longer reproduce.
