### ISSUE TITLE
Terminal Syntax Highlighting

### ISSUE THREAD

**Issue by HalosGhost** [ptpb/pb#129]
[Ix](http://ix.io) offers a feature to allow its pygments highlighter to output colors in ANSI escape codes so that, when output on the CLI (e.g., with ``curl``), you get syntax highlighting. This would be an awesome feature to add!

**Comment by buhman** [comment]
Oh, by the way, this is done in 2e1daf12a365c4f6338d175300a234aa1c99f0f2
