### ISSUE TITLE
When serving JSON responses, file-too-large should be JSON

### ISSUE THREAD

**Issue by HalosGhost** [ptpb/pb#135]
At the moment, the following is served when a file that is too large is attempted to be uploaded (even if the client specifies to receive JSON):

```html
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

As with #134, the issue with this is that the user cannot actually rely on receiving valid JSON which makes the API less predictable and consistent.

**Comment by buhman** [comment]
That response, as indicated there and in the headers, is from Nginx, not pb.

This can't be fixed without either replacing/modifying nginx, or removing that particular limitation, neither of which are attractive ideas.
