### ISSUE TITLE
The shell functions for pasting are slightly incorrect.

### ISSUE THREAD

**Issue by kitling** [ptpb/pb#137]
For lack of a better place to put this, your website has this (for example):
```bash
pb () { curl -F "c=@${1:--}" https://ptpb.pw/ }
```
where it needs to be
```bash
pb () { curl -F "c=@${1:--}" https://ptpb.pw/; }
```
It's very subtle, it's just missing a semicolon, but that causes it to fail.

**Comment by buhman** [comment]
What shell is this?

**Comment by slashbeast** [comment]
You need either new line or ; at the end of your function before you close it on any POSIX-compatible shell, bash, zsh, ask, ksh etc.  kitling is correct.

**Comment by buhman** [comment]
[well then](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10)

```
compound_list    :              term
                 | newline_list term
                 |              term separator
                 | newline_list term separator
                 ;
brace_group      : Lbrace compound_list Rbrace
                 ;
```

Shows how much I know.

**Comment by buhman** [comment]
f5c4e7437189d6a739ae54cdc1d07fa4c08cf3fb

**Comment by kitling** [comment]
Sorry, haven't been looking at Github.

Although it seems moot at this point, I will add that I was using bash on Arch Linux.
