### ISSUE TITLE
Some handlers don't seem to work

### ISSUE THREAD

**Issue by jetpacktuxedo** [ptpb/pb#158]
Specifically /f for the html form always returns `status: not found`

I sort of suspect that this might be an artifact of my configuration (and might just be something that needs more documentation)

local/pb/paste/views.py has routes defined for /s, /l, /lf, and /ls, but nothing for /f, so maybe it is being tested as though it is a paste, seeing that it isn't a valid paste, and then dumping me out there?

I'm not sure why my local install is having this issue while https://ptpb.pw/ handles it fine.

**Comment by jetpacktuxedo** [comment]
Solution for the html form handler (where $PBROOT is the root directory of your pb clone):

```
git clone https://github.com/sudokode/pbwww.git
cd pbwww
python deploy.py index.html js/index.js css/index.css > $PBROOT/pb/templates/f.html
echo '@paste.route('/f')
def html_form():
    content = render_template("f.html")
    return content' >> $PBROOT/pb.paste/views.py
```

**Comment by sudokode** [comment]
@jetpacktuxedo `pbwww` is managed separately of `pb` and, yes, it is a paste. The `/f` handler is now (somehow, I don't know the internals of `pb`) pointed at that paste: https://ptpb.pw/f/html

**Comment by jetpacktuxedo** [comment]
oh interesting, the way that I fixed it didn't use it as a paste, and I was sort of confused by what the page meant when it said it was just a paste. So the actual solution doesn't copy it into the project itself, but instead curls it to a novelty paste. 

It seems that the real problem, then, is the /r/ and /t/ handlers not working.

**Comment by buhman** [comment]
> It looks like it used to be built in, but was removed in commit 6128ee2

Correct. Interally, `/f` works exactly how it was created in 6128ee2--that is, `/f` is a regular paste with `label=f`. Creating this isn't allowed via the API, so you need to do a mongodb query to make it yourself. The way it works on ptpb is I did this for a paste that sudokode created, and sudokode can update via the API it because he knows the uuid of that paste.

**Comment by jetpacktuxedo** [comment]
Ah, that makes sense. I was trying to set it up on my local copy and couldn't write to the single character label. I didn't even think about writing it directly to the db. I ended up doing a vanity paste to /~f and changing the index to point there instead. I'll switch mine out to closer match the official implementation and maybe put some work into improving the docs for single character labels like was mentioned in #151.

**Comment by jetpacktuxedo** [comment]
Just to add onto this in case someone runs into the same issue and stumbles across this post, here is the solution I settled on to get my configuration to mirror the official one:

clone pbwww
customize index/css/js as needed
`python deploy.py index.html js/index.js css/index.css > htmlform.html`
`curl -F c=@htmlform.html http://pb.west.isilon.com:8000/~htmlform`
`mongodb pb`
`db.pastes.update( {label: "~htmlform"}, {$set: {"label": "f"}} )`

Note that it is important to write it to a file before uploading it to automatically set the mimetype. Alternatively, you can manually set the mimetype to `text/html` in the database and that should also work, but I haven't bothered to test it yet.

**Comment by buhman** [comment]
I modified your thing trivially, for clarity. Github is now stackoverflow.
