### ISSUE TITLE
Change the returned URL?

### ISSUE THREAD

**Issue by Tmplt** [ptpb/pb#164]
I have deployed `pb` on my own server, and I'm using `nginx` as a reverse proxy.
Currently, on the page itself, and when I 

```bash
echo test | curl -F c=@- "https://paste.hostname.tld"
```
the paste is created, but the `url` is `http://[::]:8080/f5-D` instead of `https://paste.hostname.tld/f5-D`. Where can I change this?

I assumed changing `VARNISH_BASE` in `/etc/xdg/pb/config.yaml` would be it, but nothing changed after I restarted `pb`.

I am using the AUR package, `pb-git`.

**Comment by buhman** [comment]
> Where can I change this?

pb calculates this from incoming request headers.

> using nginx as a reverse proxy

So nginx is the thing connecting to pb/uwsgi here?

You should add:

```conf
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Proto https;
```

To whatever block your `proxy_pass` directive is in.

**Comment by Tmplt** [comment]
My `nginx.conf` now contains:
```
location / {
    proxy_pass http://[::]:8080;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
}
```
and it works. Cheers!

**Comment by buhman** [comment]
Yep.
