### ISSUE TITLE
Well, I accidentally...

### ISSUE THREAD

**Issue by SopaXorzTaker** [ptpb/pb#168]
https://ptpb.pw/~pocsite-index.html

**Comment by SopaXorzTaker** [comment]
Seriously, this is a phishing vector and should be prevented, shouldn't it?

**Comment by jetpacktuxedo** [comment]
I'm not on the dev team for this project or anything, but I'm pretty sure this was intended as a feature and not a bug. IMO this doesn't make phishing any easier than hosting it on a personal machine.

**Comment by sudokode** [comment]
@SopaXorzTaker Not only is this a feature, but it's how /f now works: https://ptpb.pw/f/html

I don't know of another paste service that offers this sort of capability, but I can see how it could be used for great evil... https://ptpb.pw/RoPt.html (This isn't loading for me right now, getting a 504 from "awselb/2.0" @buhman have fun with AWS :P)

**Comment by silverp1** [comment]
@SopaXorzTaker definitely a feature, not a bug :+1:

**Comment by buhman** [comment]
:+1: I enjoyed reading this. This is an explicit feature, and I personally hope people find creative ways to use it.
