### ISSUE TITLE
Official instance is down?

### ISSUE THREAD

**Issue by blha303** [ptpb/pb#170]
And the certificate says it's for *.echoglobal.com, and it's signed by Comodo o.O

**Comment by jmauss** [comment]
Getting this same issue as well.

**Comment by blha303** [comment]
It wasn't TOO hard to set up my own instance at least :P I should have done it a while ago. Just thought it should be brought to someone's attention if this wasn't intentional.

**Comment by kyrias** [comment]
One of the IPs the ptpb.pw domain is pointing up seems to be down, and the other is offering a cert for echoglobal.org.

**Comment by SopaXorzTaker** [comment]
I request an immediate answer from @buhman and @silverp1, as the site may be hacked.

**Comment by silverp1** [comment]
It is fixed, @buhman migrated to AWS and it didn't go very well. Apologies.

**Comment by buhman** [comment]
Hmm, maybe I should do a write-up on each individual problem, if people are interested.

**Comment by blha303** [comment]
Sure, sounds interesting
