### ISSUE TITLE
ptpb.pw SSL certificate has expired

### ISSUE THREAD

**Issue by sudokode** [ptpb/pb#175]
Hi, it's me again. Must be that time of the year :)

https://ptpb.pw

![2016-12-01-193356_807x147_scrot](https://cloud.githubusercontent.com/assets/914109/20818741/9d03c8e4-b7fd-11e6-92df-b23c6b286fd6.png)

**Comment by buhman** [comment]
@silverp1 😢

**Comment by buhman** [comment]
Yeah, I recall jpettit adding TLS support to the original deployment a day or two after registration; makes sense that both would happen at the same time coincidentally.

**Comment by buhman** [comment]
There's confusion about who should actually do the renewal and how. Historically, we've signed all of the things via StartCom, which is now not a valid/reputable registrar due to [WoSignGate](https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates/).

**Comment by slashbeast** [comment]
You can go with Let's Encrypt. It's free and there's a lot of clients, if you do not like the default one, like 'acme-tiny' for example. Just cron it to get you new cert on bi-monthly basis (they're valid for three months) and you can forgot about it.

**Comment by buhman** [comment]
> Just cron it

I like the general idea of automating this, but not the cron part. Maybe I can consume some amazon dogfood to accomplish the same thing, only without running cron somewhere…

**Comment by slashbeast** [comment]
What's wrong in scheduled tasks in general or cron in particular?

You should've a configuration management there anyway (puppet, salt, ansible, Rex, ...) so it's kind of one-time effort. The acme client just needs to poke the Let's Encrypt API, be able to provide it a special file over http in <domain>//.well-known/acme-challenge/ and be able to write a SSL cert. You can interface it in many ways, does not need to be running as root (and in my opinion, shouldn't be)

Deploying it really depends on how your infrastructure looks like, if you use AWS ELB, you will need then to use the EC2 APi and update the cert, or actually put it on every webapp VM you have there (depends on how you configured all of it),

Anyhow, define the problem and I will provide you a solution. :)

**Comment by buhman** [comment]
https://ptpb.pw has a new certificate now.

**Comment by polyzen** [comment]
An error occurred during a connection to ptpb.pw. The server uses key pinning (HPKP) but no trusted certificate chain could be constructed that matches the pinset. Key pinning violations cannot be overridden. Error code: MOZILLA_PKIX_ERROR_KEY_PINNING_FAILURE
