### ISSUE TITLE
docker deployment

### ISSUE THREAD

**Issue by glensc** [ptpb/pb#182]
loved `pb` the second i read the feature list, wanted to try out this with local deployment immediately.

however did not find any open/closed tickets matching "docker" keyword.

are there any plans to provide `Dockerfile`, `docker-compose.yml`? shouldn't be very hard, just `pip install` or something...

or are there already known somebody's efforts? [searching docker hub](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=pb&starCount=0) for `pb` isn't exactly resultful :)

**Comment by buhman** [comment]
> however did not find any open/closed tickets matching "docker" keyword.

I currently deploy this with ECS (docker) actually. Here's a [packer template](https://ptpb.pw/j_yt/json) that I use for production.

> docker hub

Good idea. I re-tagged the last ECS image I built and pushed to dockerhub. https://hub.docker.com/r/buhman/pb/. Let me know if you have any trouble with that.
