### ISSUE TITLE
pb doesn't work behind nginx

### ISSUE THREAD

**Issue by amosbird** [ptpb/pb#183]
nginx config,
```
location /pastebin {
	    client_max_body_size 100m;
	    proxy_pass http://[::]:10002/;
	    proxy_set_header Host $host;
	    proxy_set_header X-Forwarded-Proto https;
}
```

error message of `pbpst -Sf foo.log -P .....`
```
pbpst: '[' or '{' expected near '<': 1,1
```

**Comment by amosbird** [comment]
nginx version: nginx/1.10.1
pb version: `git hash 29f64b08067a9e31865055e336fbe32fd1e61ebf1`

**Comment by buhman** [comment]
`<` at `1,1` sounds like pbpst is being fed html, while it probably expects json.

Could you reproduce this request with curl or similar, and provide the verbatim output (from nginx I guess)?

**Comment by amosbird** [comment]
@buhman thanks. I fixed this by using nginx subdomain instead of subdir proxy :smiley:

**Comment by buhman** [comment]
Ah, yeah, it's possible that was also a 404 (route does not exist) message from flask.
