### ISSUE TITLE
paste UUID lookup by paste ID

### ISSUE THREAD

**Issue by superguest** [ptpb/pb#193]
Updates and deletions require the UUID, but often times pastes are created using:
`_cmd_ | curl -F c=@- https://ptpb.pw/?u=1`, where only the url is returned.

As a result, I will not be able to make any changes to this paste.  Can you augment the API to support UUID lookup and/or updates/deletions by paste ID?

**Comment by buhman** [comment]
> Can you augment the API to support UUID lookup

I don't understand your use-case. The UUID is supposed to be the "secret" you use to manipulate the paste after creation.

If you don't know any paste metadata because you used `?u=1`, what's your expected new behavior?
 How are you going to get a non-uuid URL, if you're only capable of parsing single strings?

**Comment by superguest** [comment]
I understand what you mean.  Simply put, don't use ?u=1 if the author intends on making changes to it.
Sorry, I got confused b/c I was trying to have it both ways: have it spit out only the url and still have the ability to make changes to it afterwards.

On a digression, this is still possible if ptpb supports user accounts then the user can submit user account credentials along with the paste.  Just an idea.

**Comment by buhman** [comment]
> On a digression, this is still possible if ptpb supports user accounts then the user can submit user account credentials along with the paste. Just an idea.

Yeah, I was experimenting with a similar idea with the under-documented `namespace` feature actually. https://ptpb.pw/#namespaces

I actually don't see why I shouldn't add something like `X-Namespace-Auth` for pastes--`X-Paste-Auth`. What do you think?

**Comment by simmel** [comment]
I might be hijacking this issue but it would be nice if you could lookup shortid/sha1/etc from an uuid.

**Comment by buhman** [comment]
> it would be nice if you could lookup shortid/sha1/etc from an uuid.

What's the use case?

**Comment by buhman** [comment]
I think doing this requires a complete redesign and re-thinking of the API.

**Comment by simmel** [comment]
On Mon, 2017-10-02 at 21:33:55 +0000, Zachary Buhman wrote:
> > it would be nice if you could lookup shortid/sha1/etc from an uuid.
> 
> What's the use case?

Only having to store the uuid instead of both it and and any other.
Every other key can be used as id except the uuid.

**Comment by buhman** [comment]
> Only having to store the uuid instead of both it and and any other.

In other authorization systems you'd need to store both an identifier and a secret anyway--this is no different.
