### ISSUE TITLE
Ubuntu Installation

### ISSUE THREAD

**Issue by fStiedemann** [ptpb/pb#201]
Hey,

There are no instructions for debian/ubuntu installations. I did this:

    $ sudo apt-get install mongodb uwsgi python3-pip 
    $ git clone https://github.com/ptpb/pb.git
    $ cd pb/
    $ pip3 install -r requirements.txt
    $ chmod +x setup.py
    $ ./setup.py 

And get this error:

> ./setup.py: line 3: syntax error near unexpected token `newline'
> ./setup.py: line 3: `setuptools.setup('

How exactly do I install pb in ubuntu 16?

**Comment by ragaraga** [comment]
hello i did `pip3 install .` and everything installed successfully. mondodb is listening, how do i start pb now? can you recommend a systemd pb.service conf?

**Comment by buhman** [comment]
> how do i start pb now?

In my opinion, docker is the best way to do pretty much everything. The docker-compose file that pb ships with works great.

> can you recommend a systemd pb.service conf?

Unrelated to what I just said, [this pb.service](https://github.com/ptpb/pb/blob/master/pkg/pb.service) still looks pretty valid provided you have uwsgi install on a distribution like archlinux that ships a `uwsgi@.service`, and have a `pb.ini` in the correct place.

Another alternative is to just run:

`python -m pb`

**Comment by jowypej** [comment]
$ uname -a
    Linux server 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux


	user@server:/var/www/pb$ python -m pb

	Traceback (most recent call last):
	  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
	    "__main__", fname, loader, pkg_name)
	  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
	    exec code in run_globals
	  File "/var/www/pb/pb/__main__.py", line 17, in <module>
	    import sys, __main__
	  File "pb/__main__.py", line 31, in <module>
	    from pb import db
	  File "pb/pb.py", line 15, in <module>
	    from pb.cache import init_cache
	ImportError: No module named cache

	user@server:/var/www/pb$ python3 -m pb

	Traceback (most recent call last):
	  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
	    "__main__", mod_spec)
	  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
	    exec(code, run_globals)
	  File "/var/www/pb/pb/__main__.py", line 21, in <module>
	    p = path(p).resolve()
	  File "/usr/lib/python3.5/pathlib.py", line 1109, in resolve
	    s = self._flavour.resolve(self)
	  File "/usr/lib/python3.5/pathlib.py", line 330, in resolve
	    return _resolve(base, str(path)) or sep
	  File "/usr/lib/python3.5/pathlib.py", line 315, in _resolve
	    target = accessor.readlink(newpath)
	  File "/usr/lib/python3.5/pathlib.py", line 422, in readlink
	    return os.readlink(path)
	FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python35.zip'

	user@server:/var/www/pb$ 

Any advice?

**Comment by buhman** [comment]
> ImportError: No module named cache

This is because python2's import mechanism by default is relative, while some of `pb` imports depend on python3-style `absolute_import`. pb overall is not compatible with python2 in other ways as well.

> FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python35.zip'

It looks like your python3.5 installation is incomplete. Maybe try making sure it is completely installed with: 

```bash
apt-get install python3
```

Also if you're using anything older than debian stretch (jessie/wheezy), that version of python3 will be too old as well.

**Comment by buhman** [comment]
IMO, working with system python installations is a massive pain. You might also try this easy 3-step docker deployment method:

1) Install docker

https://docs.docker.com/engine/installation/linux/docker-ce/debian/#install-docker-ce

2) start mongo

```
docker run -d --name mongodb mongo
```

3) start pb

```
docker run -d --link mongodb --publish 10002:10002 ptpb/pb
```

Verify with `curl http://localhost:10002`

**Comment by jowypej** [comment]
Thanks so much. The docker installation you linked to was helpful.
