### ISSUE TITLE
In short - can this project considered dead?

### ISSUE THREAD

**Issue by agaida** [ptpb/pb#202]

**Comment by buhman** [comment]
No.

**Comment by buhman** [comment]
The API is actively used by many users and tools, and the production deployment isn't going anywhere.

New feature requests would be considered, valid contributions accepted, etc…

**Comment by sudokode** [comment]
lolwat

**Comment by agaida** [comment]
ummh - was only asking because of pbs/#1

**Comment by buhman** [comment]
I guess I'm not properly following that repo; I had no idea there were two issues. Thanks!

**Comment by agaida** [comment]
@buhman - we (siduction) was in search for a new pastebin after running our current solution for six or seven years - and i  guess we found it in pb. So our ultimate goal was to get it up and running firsthand. Ok, took me some time on a current debian - but if i run into problems within the installation process and found ancient bugs about that raise questions. Sorry about the wording, pb is up and running now and it is great. Will get into production i think within the next few weeks with our new release.

**Comment by buhman** [comment]
That's great to hear!
