### ISSUE TITLE
pasting content does not work

### ISSUE THREAD

**Issue by Cephra** [ptpb/pb#206]
When I run:
echo "something" | curl -F c=@- https://ptpb.pw/
I get this:
status: no post content

Why is this happening?

**Comment by buhman** [comment]
> Why is this happening?

Are you running curl `7.56.0` ? There was a regression in that exact version that was fixed in `7.56.1`.

**Comment by Cephra** [comment]
Yeah I'm running exactly that. Gonna have to upgrade then. Thank you for the quick help!
