### ISSUE TITLE
Raspberry pi installation?

### ISSUE THREAD

**Issue by eubwxidc** [ptpb/pb#207]
Just tried the pb docker image on rpi3 running ubuntu mate but I don't think the pi architecture is supported by your docker image. Is this something you can easily include in the docker image? Is it possible to install pb on raspberry pis?

**Comment by eubwxidc** [comment]
Thanks for the reply. I've never created a docker image before. Would you be able to assist?

**Comment by buhman** [comment]
You should be able to literally replace the base in the dockerfile, and build using `docker build .`

**Comment by buhman** [comment]
Did you get this to work? I do think having some easy way to deploy pb on arm hardware is valuable, so I'm interested in "officially" supporting this.

**Comment by eubwxidc** [comment]
I honestly have no clue how to use docker or "replace the base". But I'll have some time tomorrow so I'll look into it and give it a try. I would love to get this setup on the pi on my home network.

**Comment by silverp1** [comment]
@eubwxidc essentially just replace this line with one of the recommended ones: https://github.com/ptpb/pb/blob/master/Dockerfile#L1

**Comment by buhman** [comment]
I've been considering getting arm hardware myself, so this is definitely something that interests me. Let me know if this works for you!
