### ISSUE TITLE
Using pb with PowerShell?

### ISSUE THREAD

**Issue by tokyoneon** [ptpb/pb#212]
@buhman @silverp1 

Hey guys, is it possible to upload files using PowerShell instead of cURL? I couldn't figure it out.

	> powershell Invoke-RestMethod -Uri 'https://ptpb.pw/~somevanity' -Method POST -InFile .\script.py

**Comment by buhman** [comment]
According to https://ptpb.pw/a you can't (currently) provide the paste content directly in the request body. IIRC this wasn't the case at some point, but was removed I think.

---

Wow there are a ton of completely awful examples of how to do this in powershell...

You could do something like this (less code):

https://stackoverflow.com/questions/36268925/powershell-invoke-restmethod-multipart-form-data

... but afaict, the "correct"+minimum way to do it is something more like this:

```
$multipartContent = [System.Net.Http.MultipartFormDataContent]::new()
$FileStream = [System.IO.FileStream]::new(".\script.py", [System.IO.FileMode]::Open)
$fileHeader = [System.Net.Http.Headers.ContentDispositionHeaderValue]::new("form-data")
$fileHeader.Name = "c"
$fileContent = [System.Net.Http.StreamContent]::new($FileStream)
$fileContent.Headers.ContentDisposition = $fileHeader
$multipartContent.Add($fileContent)

Invoke-WebRequest -Uri "https://ptpb.pw/~somevanity" -Body $multipartContent -Method 'POST'
```

I got this by reading the upstream documentation for [Invoke-RestMethod](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6) which references the existance of `System.Net.Http.MultipartFormDataContent`, which I found an example for in [Invoke-WebRequest](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-6#examples).

I haven't finished compiling powershell for my platform yet, but I'm mildly certain this should work with at worst minor tweaks.

**Comment by tokyoneon** [comment]
I really appreciate the comprehensive answer. Thank you.
