### ISSUE TITLE
Highlight multiple lines

### ISSUE THREAD

**Issue by baco** [ptpb/pb#215]
Add the ability to highlight more than just one line (`#L-6`), for instance multiple lines, `#L-6,8,10` or blocks ranges `#L-6:L-9`.

**Comment by buhman** [comment]
I suspect this is harder to do with pure CSS selectors; I'll look at what github and similar do.

**Comment by buhman** [comment]
When you select one or multiple lines on github, some event listeners add/remove a `highlight` class from the DOM. This means that it likely does at least:

* listen for a click event or url hash change
* suppress the default event action
* parse the current url hash
* re-slice the block depending on the modifier keys currently pressed
* update the DOM + url hash

pb uses the css `:target` selector instead, which depends on the current url fragment. It is not possible for a url fragment to directly represent "ranges of anchors".

**Comment by buhman** [comment]
Similar to how `/f` is [actually a SPA](https://github.com/sudokode/pbwww), this should be a new `pb-highlighter` SPA.

Provided someone (including me) is willing to write such a SPA, I'm also willing to update pb and/or the ptpb.pw deployment to provide convenience shortcuts to said SPA.

That in mind, I'm closing this, as written, as `wontfix`.
