### ISSUE TITLE
TOML syntax highlighting

### ISSUE THREAD

**Issue by kaushalmodi** [ptpb/pb#221]
Can we have syntax highlighting for [TOML][1]? There are many TOML parser [implementations][2] if they can serve as the proof of popularity. The aim is to have links like https://ptpb.pw/cg9R (small TOML snippet) be syntax highlighted using https://ptpb.pw/cg9R/toml.

For example, it looks like this in Emacs:

![image](https://user-images.githubusercontent.com/3578197/43867942-4b0efbfa-9b39-11e8-802e-db66d33660f9.png)

[1]: https://github.com/toml-lang/toml
[2]: https://github.com/toml-lang/toml/wiki#implementations

**Comment by buhman** [comment]
This is not as trivial as implied.

> TOML parser implementations

Actually these are TOML codecs, which aren't directly useful if they don't provide a standalone-usable parser/lexer interface.

It's not just a matter dropping in a random, the tokens emitted by that lexer also would need to use pygments' token model.

**Comment by buhman** [comment]
This looks directly usable, if valid to begin with:

https://github.com/liluo/pygments-github-lexers/blob/master/pygments_github_lexers/github.py

**Comment by buhman** [comment]
I integrated pygments_github_lexers for toml and puppet in [custom-lexers](https://github.com/ptpb/pb/tree/custom-lexers). Unfortunately, github crashes while attempting to generate a diff for that, so I'm unable to create a pull request.

More importantly, that lexer is completely garbage, and looks awful:

![](https://ptpb.pw/mkeN.png)

Compare that with how the `cfg` lexer parses this:

![](https://ptpb.pw/dAzP.png)

**Comment by buhman** [comment]
As a consquence, I'm going to close this as:

- wontfix
- patcheswelcome
- upstreambug

As all of these are applicable.

**Comment by buhman** [comment]
On the other hand, if you really want the first version as-is, I'm happy to merge terrible lexers.

**Comment by kaushalmodi** [comment]
I agree that that lexer is terrible, but at least it is not highlighting things incorrectly. The cfg (ini?) lexer works for the simple example. But https://ptpb.pw/cg9R/cfg looks really bad:

![image](https://user-images.githubusercontent.com/3578197/43875020-ee35d4e8-9b5c-11e8-8d79-8105cc3a6c24.png)

Does that incomplete toml lexer look that bad?

**Comment by buhman** [comment]
!()[https://ptpb.pw/a7Pl.png]

**Comment by kaushalmodi** [comment]
@buhman I think that that lexer looks nice. The only issue is that it's not setting the color of **keys** differently.. but it recognizes strings, comments, keys with indentation, etc.

**Comment by buhman** [comment]
I haven't actually read the spec, but how does this look:

![](https://ptpb.pw/QoMw.png)

**Comment by kaushalmodi** [comment]
That looks nice!

**Comment by kaushalmodi** [comment]
If you like to add a full fledged test, here's a larger toml snippet: https://ptpb.pw/WwKU

**Comment by buhman** [comment]
https://ptpb.pw/WwKU/toml
