### ISSUE TITLE
Org mode syntax highlighting

### ISSUE THREAD

**Issue by kaushalmodi** [ptpb/pb#222]
Hello,

Org mode ( https://orgmode.org/ ) is a "markup" language like Markdown (but better).

Unfortunately, Pygments doesn't support Org mode highlighting; there's an [issue open][1].

But I recently added support for Org mode syntax highlighting to [Chroma][2]. It is a Go library for syntax highlighting (equivalent of Pygments in Python), but it also provides a [CLI utility][3]. 

Here's an example of how the Chroma-highlighted Org mode code block looks -- See the colorful code block at the end of [this page][4].

---

**Is using an external binary to returned colorized HTML something that you would consider?**

[1]: https://bitbucket.org/birkenfeld/pygments-main/issues/719/wishlist-support-org
[2]: https://github.com/alecthomas/chroma
[3]: https://github.com/alecthomas/chroma#command-line-interface
[4]: https://ox-hugo.scripter.co/doc/table-styling/

**Comment by buhman** [comment]
> something that you would consider

Absolutely not :)

**Comment by kaushalmodi** [comment]
Oh well, I thought, it would hurt asking. Thanks :)
