### ISSUE TITLE
Prevent user selection of line numbers

### ISSUE THREAD

**Issue by dustinpaluch** [ptpb/pb#227]
It would be nice if _Select All + Copy_ didn't include the line numbers. I recommend adding this CSS to the `linenos` class:

```
user-select: none;
-moz-user-select: none;
-webkit-user-select: none;
-ms-user-select: none;
```

**Comment by buhman** [comment]
https://github.com/ptpb/pbs/commit/96a4488cf56c8259fa642618a8b9e29fc26388f2

Thanks!

**Comment by buhman** [comment]
This is deployed, but it might take awhile for the CDN hosting it to expire.

**Comment by dustinpaluch** [comment]
@buhman you'll need the prefixed properties too if you want to support non-chrome browsers.
https://caniuse.com/#search=user-select

**Comment by dustinpaluch** [comment]
@buhman, any love for non-chrome browsers?

**Comment by buhman** [comment]
I tested this on firefox and chrome. If there's anything more obscure than either of those I'm not really interested.

**Comment by dustinpaluch** [comment]
It won't work in firefox unless you include the `-moz-user-select` property.

![screen shot 2018-08-29 at 8 57 54 am](https://user-images.githubusercontent.com/6547887/44792691-1ad74a00-ab6a-11e8-963e-135e6f68ab77.png)

**Comment by dustinpaluch** [comment]
@buhman would you mind double checking firefox support for this feature?
