### ISSUE TITLE
Ubuntu/docker installation issue

### ISSUE THREAD

**Issue by dufywihi** [ptpb/pb#229]
using xenial, installed docker:

https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04

then installed `docker-compose` from the ubuntu repos (no package called `docker-compose` found in docker repos)

then git cloned the pb repo into /opt. then ran:

    docker-compose up

	ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
	For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

the docker-compose version found in xenial is v1.8.0. what am i getting wrong here?

**Comment by buhman** [comment]
> what am i getting wrong here

Your docker-compose version is too old, as said poorly in the error message. 1.8.0 supports compose file version `<=2.0` while pb specifies `=3.2`.

---

I suggest the "Linux" instructions here (curl + chmod):

https://docs.docker.com/compose/install/#install-compose
