### ISSUE TITLE
How to host instance with TLS

### ISSUE THREAD

**Issue by therocode** [ptpb/pb#231]
Hosting an instance of pb is really simple using the docker file, however this makes it listen as a normal http server, not https. As far as I could see, there are no options in the docker file to host it with TLS. What's the best practice of doing such?

**Comment by buhman** [comment]
> What's the best practice of doing such?

Not sure.

> host it with TLS

The ptpb.pw deployment uses nginx for ssl termination, combined with proxy_pass. The config used is:

```
server {
	listen 443 default_server;
	listen [::]:443 default_server;

	client_max_body_size 64M;

	server_name _;

	ssl    on;
	ssl_certificate    /etc/letsencrypt/live/ptpb.pw/fullchain.pem;
	ssl_certificate_key    /etc/letsencrypt/live/ptpb.pw/privkey.pem;

	location / {
    		proxy_pass       http://localhost:6081;
    		proxy_set_header Host      $host;
    		proxy_set_header X-Forwarded-Proto https;
	}
}
```

If you wanted to do the same thing, I suggest you use this configuration verbatim, possibly with other additional directives if desired.

**Comment by therocode** [comment]
Thanks for the information, appreciated!

Eventrually having it as a docker image would certainly be helpful for people with not much experience in setting up hosted systems (like me).

Thanks!
