### ISSUE TITLE
IP upload black/whitelist

### ISSUE THREAD

**Issue by jerbear64** [ptpb/pb#233]
Is there a way to prevent certain IP's or identities from creating pastes on an instance, while still allowing them to view contents? I'm also wondering if the reverse of this is possible, only allowing whitelisted addresses/keys to upload.

**Comment by buhman** [comment]
You could do this with nginx.

https://docs.nginx.com/nginx/admin-guide/security-controls/blacklisting-ip-addresses/

It supports whitelist/blacklist depending on how you use `allow all`/`deny all`.

> only allowing whitelisted addresses/keys to upload

Something like:

```
limit_except GET {
    allow 1.2.3.4/32;
    deny all;
}
```

This reads like "for all methods other than GET, allow $ip, otherwise deny".
