### ISSUE TITLE
Rules for automatic paste removal?

### ISSUE THREAD

**Issue by megitu** [ptpb/pb#238]
I can not find any rules when pastes on https://ptpb.pw/ are automatically removed.
Could you please give me any link to such an info or describe it here?

**Comment by buhman** [comment]
> What is the default data retention policy?

By default, pastes exist indefinitely. 

The oldest paste in the ptpb.pw database is `2015-02-28T11:49:42.141Z`

> What is the [`sunset`](https://ptpb.pw/#sunsetting-pastes) data retention policy?

If a paste is created with the sunset feature, the paste will be deleted only if both of these conditions are simultaneously true:

- the current time is greater than the paste's `sunset` value
- the paste is referenced by any request (`GET`, `PUT`, etc..)

This triggers an `expired` response, which does not yield the paste content, and permanently removes the paste from the database.

**Comment by buhman** [comment]
"indefinite" is also provided on a best-effort basis. Pastes are not backed up, and would not be restored in the event of some catastrophic failure.
