### ISSUE TITLE
ptpb.pw is out of disk space

### ISSUE THREAD

**Issue by buhman** [ptpb/pb#240]
I freed about 500MB by deleting all pastes over 60MB, just to keep the service going, but this obviously isn't going to last very long.

We should redeploy ptpb.pw within the next day probably.

**Comment by buhman** [comment]
ptpb.pw was migrated

**Comment by buhman** [comment]
I don't see this documented elsewhere, but I found at the time that this unexpected increase in utilization was caused by pb being used as a bulk photo backup service.

**Comment by cup** [comment]
https://github.com/ptpb/pb/issues/245

**Comment by cup** [comment]
https://github.com/ptpb/pb/issues/240
https://github.com/ptpb/pb/issues/245
https://github.com/ptpb/pb/issues/246

**Comment by mpan-pl** [comment]
Out of curiosity: during normal operation, how much space was the data taking and how many upload/download requests was ptpb.pw experiencing?

**Comment by buhman** [comment]
I do not have record of this.

From memory, ptpb.pw had accumulated ~60GB in paste content from ~2014 to ~Nov, 2018. Over roughly 2 weeks, this inflated to fill the available ~150GB, which caused an outage.

Paste records are datetime-stamped, and I'm open to making a public-paste-only database dump available if someone is interested in analysis.
