### ISSUE TITLE
What does "ptpb.pw" mean? 

### ISSUE THREAD

**Issue by kaushalmodi** [ptpb/pb#241]
Does the domain have a meaning? I.e. is it a mnemonic or acronym of something?

I can see that "pb" from "pt**pb**.pw" could stand for "pastebin". But what are "pt" and "pw"?

_platinum lead phosphorus tungsten_

**Comment by buhman** [comment]
It's a semi-backronym for:

the jPettiT PasteBin, Patches Welcome
