### ISSUE TITLE
how to add the command executed in the paste

### ISSUE THREAD

**Issue by g4570n** [ptpb/pb#242]
For example, if I execute the following: 

`uname -s | curl -F c=@- https://ptpb.pw/` 

the content of the paste will be:

`Linux`

How can I get the paste to contain the command used + the result, something like this:

```
$ uname -s
Linux
```

**Comment by buhman** [comment]
Not sure if I understand.

you mean like this?:

```shell-session
$ uname -s | tee >(curl -F c=@- https://ptpb.pw)
Linux
date: 2015-03-05T13:00:31.248000+00:00
digest: cd4bf5db2601ec9075425102d2b12a9ee5413d4a
long: AM1L9dsmAeyQdUJRAtKxKp7lQT1K
short: QT1K
size: 6
status: already exists
url: https://ptpb.pw/QT1K
```

**Comment by glensc** [comment]
@buhman he wants first line of paste to be command he executed on pipe. i don't think there's good way to do that without extra script.

**Comment by buhman** [comment]
> first line of paste to be command he executed on pipe

```
$ bash -xc "uname -s" | curl -F c=@- https://ptpb.pw/
date: 2019-01-07T01:41:25.538891+00:00
digest: fd7589f1613ca881061dfe6a5f2722c0c3894085
long: AP11ifFhPKiBBh3-al8nIsDDiUCF
short: iUCF
size: 17
status: created
url: https://ptpb.pw/iUCF
uuid: f3ffde45-c452-4ddf-bb12-c8540744a2c2
➜  ~ curl https://ptpb.pw/iUCF
+ uname -s
Linux
```

**Comment by g4570n** [comment]
Thanks @buhman , something like that was what I was referring to, similar to what it does: `wgetpaste -c`

**Comment by buhman** [comment]
> is there an example that doesn't involve shell-quoting?

Sure..

```
$ bash -x << EOF | curl -F c=@- https://ptpb.pw/
uname -s
EOF
```

> and the example doesn't work with bash3

ancient/obscure shells are not really interesting, but:

```
$ bash -xc "uname -s" 2>&1 | curl -F c=@- https://ptpb.pw/
```

**Comment by glensc** [comment]
latest macOS /bin/bash is 3.2.57, so it's not that uncommon and the system itself is not ancient.

not sure why they don't update newer, perhaps GPL v2 -> GPL v3 change in bash license not compatible for re-distribution inside the OS?
