### ISSUE TITLE
post request header storage and replay

### ISSUE THREAD

**Issue by eddyb** [ptpb/pb#243]
AFAIK, both of these are required to display a `.svgz` (gzip-compressed SVG) file:
```http
Content-Type: image/svg+xml
Content-Encoding: gzip
```
But currently only the first header is sent, so the browser tries to interpret the file as an uncompressed SVG file, and fails. My testcase is https://ptpb.pw/9sCt.svgz.

See also https://github.com/h5bp/server-configs-nginx/issues/86 for another example where this kind of issue cropped up.

**Comment by buhman** [comment]
> Content-Encoding: gzip

This isn't really a content-type issue, because there's no such thing as "image/svg+xml+gzip", which is why `.svgz` doesn't do anything useful.

If this feature were implemented, it would be more of a "store and replay POST headers on GET"; something like:

```
curl -F c=@my.svgz -H "Content-Encoding: gzip" https://ptpb.pw
```

**Comment by buhman** [comment]
This is something I've thought pb has needed for awhile, but nobody ever requested it or presented a meaningful use-case.

**Comment by buhman** [comment]
implemented in: a8a1706693f46451b6b6e48ed79349b84485b43d
deployed via: [`ptpb-deploy/82`](https://circleci.com/gh/ptpb/ptpb-deploy/82)

Example:

```
➜  ~ curl -F c=@- -H 'x-foo-bar: spam' https://ptpb.pw <<< gook2134
date: 2019-01-07T03:13:36.533698+00:00
digest: 93c1103b89d5e04ab2f4a21601f16a9df53f7289
long: AJPBEDuJ1eBKsvSiFgHxap31P3KJ
short: P3KJ
size: 9
status: created
url: https://ptpb.pw/P3KJ
uuid: 9c54b52e-1e79-4b7a-b0e9-2c004088d7da
➜  ~ curl https://ptpb.pw/P3KJ
gook2134
➜  ~ curl -D- https://ptpb.pw/P3KJ
HTTP/1.1 200 OK
Server: openresty/1.13.6.2
Date: Mon, 07 Jan 2019 03:13:43 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 9
Connection: keep-alive
x-foo-bar: spam
x-varnish: 32774
ETag: "paste-93c1103b89d5e04ab2f4a21601f16a9df53f7289"
Cache-Control: public, max-age=43200
X-Varnish: 13 11
Age: 2
Via: 1.1 varnish (Varnish/6.0)
Accept-Ranges: bytes

gook2134
```

In your case, you want to add `-H 'content-encoding: gzip'` to your regular curl arguments.

**Comment by buhman** [comment]
As another example, here's a png that with `content-disposition: attachment` (will trigger download dialog instead of rendering):

https://ptpb.pw/0OAB.png

**Comment by buhman** [comment]
Interestingly, varnish is trying to be "[smart](https://varnish-cache.org/docs/trunk/users-guide/compression.html)", which confounds testing:

```
$ curl -s -D- https://ptpb.pw/McM6 | wc 
   1298   12249  109818
$ curl -H 'Accept-Encoding: gzip' -s -D- https://ptpb.pw/McM6 | wc 
    121     571   22832
```

**Comment by buhman** [comment]
```
$ curl -s https://ptpb.pw/jX4G | mpv /dev/stdin
Playing: /dev/stdin
Failed to recognize file format.


Exiting... (Errors when loading file)
```

```
curl -s https://ptpb.pw/jX4G | gzip -d | mpv /dev/stdin
Playing: /dev/stdin
[mkv] SeekHead position beyond end of file - incomplete file?
 (+) Video --vid=1 (*) (vp9 1920x1080 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) (vorbis 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
AV: 00:00:01 / 00:04:07 (0%) A-V:  0.000 Cache: 124s+15MB


Exiting... (Quit)
```

And indeed, https://ptpb.pw/jX4G.webm works in firefox/chromium automatically.
