### ISSUE TITLE
update won't work

### ISSUE THREAD

**Issue by p1839251** [ptpb/pb#244]
Hi,
I've been trying updating my original post but I just can't do that:

`$ echo "brand-new paste" | curl -F sunset=60 -F c=@- https://ptpb.pw/~vanitypaste`

> date: 2019-02-25T20:59:44.359002+00:00
> digest: 390b23c0986e3645f632ad80195486c52377960d
> label: ~vanitypaste
> long: ADkLI8CYbjZF9jKtgBlUhsUjd5YN
> short: d5YN
> size: 16
> status: created
> sunset: 2019-02-25T21:00:44.330479+00:00
> url: https://ptpb.pw/~vanitypaste
> uuid: 9ee30759-7829-4292-a775-aeff6097460e

`$ curl https://ptpb.pw/~vanitypaste`

> brand-new paste

`$ echo 'even newer paste' | curl -X PUT -F c=@- https://ptpb.pw/9ee30759-7829-4292-a775-aeff6097460e`

> date: 2019-02-25T20:59:44.359000+00:00
> digest: 2da78e8247b8b4d80303daac3340a68bf043fa6d
> label: ~vanitypaste
> long: AC2njoJHuLTYAwParDNApovwQ_pt
> short: Q_pt
> size: 17
> **status: updated**
> sunset: 2019-02-25T21:00:44.330000+00:00
> url: https://ptpb.pw/~vanitypaste

`$ curl https://ptpb.pw/~vanitypaste`

> brand-new paste

**Comment by buhman** [comment]
Thanks for reporting this. This is a caching issue--the intended behavior is that the cache is invalidated on PUT, but clearly this isn't happening.
