### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by worldworm** [ptpb/pb#250]
Does this site relates to your project?
https://ptpb.pw/
It is not available.

If the URL has changed, please open a pull request at 
https://github.com/Kickball/awesome-selfhosted or create an issue. Thank you!

https://github.com/Kickball/awesome-selfhosted/issues/1767

**Comment by glensc** [comment]
@worldworm, yes, it was shut down: https://github.com/ptpb/pb/issues/246

this is also mentioned in project readme: https://github.com/ptpb/pb#overview

@buhman: maybe keep that issue open and pinned?

**Comment by worldworm** [comment]
Thanks for your quick answer!
Is there a plan to open a demo page again in the future? Otherwise I would remove the page from the list and only link to the github repo.

**Comment by glensc** [comment]
You can read about the plans and future from the issue I linked.

In short, the answer is likely no, as it would be abused by coiners again, be it a demo or actual service.

And I don't get the list then, if there's no public service, the software can't be listed as self-hosted service? And why you need a demo for pastebin-like service? it will be some HTTP service that just responds "URL to use" when you post there.

**Comment by worldworm** [comment]
Thanks for your response.

> In short, the answer is likely no, as it would be abused by coiners again, be it a demo or actual service.

Then i will remove the demo link from the list, so that only the github repo link is refering. If a new demo instance will be opened, feel free to reopen this issue or open a pr at awesome-selfhosted

> And I don't get the list then, if there's no public service, the software can't be listed as self-hosted service? And why you need a demo for pastebin-like service? it will be some HTTP service that just responds "URL to use" when you post there.

The list provides lots of software that is selfhostable. To get a better understanding there are lots of demo links provided. A better explanation can be found here: https://github.com/Kickball/awesome-selfhosted#awesome-selfhosted

**Comment by buhman** [comment]
@glensc nice, I didn't know about that feature, thanks!
