### ISSUE TITLE
Question: Private paste vs Non-private paste

### ISSUE THREAD

**Issue by hermanzdosilovic** [ptpb/pb#255]
Hi,

can you please briefly explain the difference between private pastes and non-private pastes?

What is advantage and disadvantage of using private pastes?

Thank you.

BR,
Herman

**Comment by buhman** [comment]
"private" just means that it has a longer URL.

Advantage: it is (significantly) harder to guess a "private" URL

Disadvantage: it is (significantly) harder to memorize/type a "private" URL. For example, sometimes I would use ptpb.pw to transfer a file to a machine that I can't easily copy-paste the URL to. In this case I would have used a non-private paste.

**Comment by buhman** [comment]
The original thinking behind "private" pastes was also that your paste would never "collide" with any other paste, whereas this is more likely with a non-"private" paste. This private paste non-collision property is as unlikely as a full sha1 collision.

For non-private, when two pastes have a shared sha1 prefix, the less-recent paste is shadowed by the more recent paste.

**Comment by buhman** [comment]
In summary, the feature is useful, but perhaps not named well.

**Comment by hermanzdosilovic** [comment]
Thank you @buhman for your answer. :)
